// Source: Company Handbook v1.0, Chapter 5 (Curriculum) and 9.1 (Tools).

export type Module = {
  code: string;
  slug: string;
  stage: string;
  title: string;
  /** Public-facing label used on overview pages. */
  shortTitle: string;
  oneLiner: string;
  level: string;
  outcome: string;
  deliverable: string;
  topics: string[];
};

export const modules: Module[] = [
  {
    code: "A",
    slug: "research-foundations",
    stage: "1",
    title: "Research Foundations",
    shortTitle: "Research Foundations",
    oneLiner: "Turn a problem into a research question.",
    level: "Beginner",
    outcome: "Understand the research process and turn a problem into a research question.",
    deliverable: "One research question with rationale and a preliminary literature map.",
    topics: [
      "Research question development: topic → problem → gap → question",
      "PICO, PECO and other question frameworks",
      "Efficient literature searching",
      "Primary versus secondary research",
      "Observational versus experimental designs, and choosing the right study design",
      "Research ethics, plagiarism, authorship and publication ethics",
      "Introduction to PubMed, Google Scholar, and Scopus and Web of Science concepts",
      "Reference management: Zotero and Mendeley basics",
      "Introduction to Excel and R for research",
    ],
  },
  {
    code: "B",
    slug: "letter-to-the-editor",
    stage: "2",
    title: "Letter to the Editor",
    shortTitle: "Scholarly Writing",
    oneLiner: "Write and submit a letter to the editor.",
    level: "Beginner",
    outcome: "Write and submit a concise scholarly response.",
    deliverable: "A submission-ready letter based on a published article.",
    topics: [
      "Finding suitable topics: recent papers, controversies, methodological concerns and important findings",
      "Types of letter: commentary, critique, clarification and brief scientific response",
      "Reading a target article critically",
      "Structure: opening context → key point → evidence → interpretation → closing",
      "Keeping the argument focused and evidence-based",
      "References and citation style",
      "Finding suitable journals: scope, article types, word limits and submission requirements",
      "Cover letter and submission checklist",
      "Common reasons letters are rejected",
    ],
  },
  {
    code: "C",
    slug: "narrative-review",
    stage: "3",
    title: "Narrative Review",
    shortTitle: "Literature Reviews",
    oneLiner: "Synthesize literature into a structured review.",
    level: "Beginner to Intermediate",
    outcome: "Synthesize literature and write a structured review.",
    deliverable: "A complete narrative review manuscript outline with selected written sections.",
    topics: [
      "Topic selection and scope control: broad topic versus focused review question",
      "Building a literature search strategy",
      "Organizing evidence into themes",
      "Introduction and rationale",
      "Main body: thematic synthesis rather than article-by-article summary",
      "Critical interpretation and identification of gaps",
      "Conclusion and future directions",
      "Citation management and avoiding citation dumping",
      "Tables, figures and conceptual frameworks",
      "Choosing a target journal and following author guidelines",
    ],
  },
  {
    code: "D",
    slug: "cross-sectional-study",
    stage: "4",
    title: "Cross-sectional Study",
    shortTitle: "Research Studies",
    oneLiner: "Design, collect and analyze primary data.",
    level: "Intermediate",
    outcome: "Design, collect and analyze primary data.",
    deliverable: "Protocol, questionnaire, sample-size calculation, analysis plan and manuscript draft.",
    topics: [
      "Choosing a feasible research question",
      "Defining the population, exposure and outcome variables",
      "Inclusion and exclusion criteria",
      "Questionnaire development: domains, item construction and response options",
      "Content validity, pilot testing and reliability concepts",
      "Sampling methods and sampling bias",
      "Sample-size calculation for prevalence and associations",
      "Data dictionary and coding plan",
      "Ethics approval, consent and data-collection workflow",
      "Data cleaning and missing-data checks",
      "Descriptive statistics and appropriate inferential tests",
      "Effect measures and confidence intervals",
      "Writing the Introduction, Methods, Results and Discussion",
      "Reporting with the appropriate reporting guideline",
    ],
  },
  {
    code: "E",
    slug: "original-study-analysis",
    stage: "5",
    title: "Original Study Analysis",
    shortTitle: "Statistical Analysis",
    oneLiner: "Descriptive, inferential and regression analysis.",
    level: "Intermediate",
    outcome: "Perform descriptive, inferential and regression analyses.",
    deliverable: "An analysis report with tables, figures, statistical tests and interpretation.",
    topics: [
      "Data structure and variable types",
      "Data cleaning and quality checks",
      "Descriptive analysis: mean and SD, median and IQR, proportions and distributions",
      "Normality and graphical exploration",
      "Choosing inferential tests based on the question and the data",
      "t-test, Mann–Whitney U, ANOVA and Kruskal–Wallis",
      "Chi-square and Fisher's exact test",
      "Correlation",
      "Effect sizes and confidence intervals",
      "Confounding, and why association is not causation",
      "Linear and logistic regression",
      "Model interpretation, assumptions, diagnostics and common errors",
      "Reproducible analysis in R",
    ],
  },
  {
    code: "F",
    slug: "systematic-review-and-meta-analysis",
    stage: "6",
    title: "Systematic Review and Meta-analysis",
    shortTitle: "Systematic Review & Meta-analysis",
    oneLiner: "Evidence synthesis from protocol to manuscript.",
    level: "Intermediate to Advanced",
    outcome: "Complete an evidence synthesis from protocol to manuscript.",
    deliverable: "A complete mini systematic review and meta-analysis, from search strategy to manuscript.",
    topics: [
      "Topic selection, feasibility and a focused review question",
      "Protocol development and registration concepts",
      "Search-string generation: keywords, synonyms, MeSH and other controlled vocabulary, and Boolean operators",
      "Database searching, deduplication and screening",
      "Title and abstract screening versus full-text screening; inclusion and exclusion criteria",
      "PRISMA flow diagram",
      "Data-extraction sheet design",
      "Risk-of-bias assessment by study design",
      "Effect measures: RR, OR, MD, SMD, HR and others",
      "Fixed-effect versus random-effects models",
      "Heterogeneity and I²; forest plots",
      "Subgroup and sensitivity analyses",
      "Publication bias and funnel plots",
      "Certainty of evidence and GRADE",
      "Manuscript writing and PRISMA reporting",
    ],
  },
  {
    code: "G",
    slug: "advanced-meta-analysis",
    stage: "7",
    title: "Advanced Meta-analysis",
    shortTitle: "Advanced Methods",
    oneLiner: "Meta-regression, prevalence, DTA and TSA.",
    level: "Advanced",
    outcome: "Apply meta-regression, prevalence, DTA and TSA methods.",
    deliverable: "One advanced analysis project using a real evidence-synthesis dataset.",
    topics: [
      "Meta-regression: rationale, moderators and interpretation",
      "Prevalence meta-analysis",
      "Zero-event studies and sparse data",
      "Diagnostic test accuracy meta-analysis: sensitivity, specificity and hierarchical models",
      "Trial Sequential Analysis: information size, monitoring boundaries and interpretation",
      "Advanced sensitivity analyses",
      "Clinical and methodological heterogeneity",
      "Avoiding over-interpretation of advanced analyses",
    ],
  },
  {
    code: "H",
    slug: "public-health-data-cdc-gbd",
    stage: "8",
    title: "Public Health Data: CDC and GBD",
    shortTitle: "Public Health Data",
    oneLiner: "Population research with CDC and GBD data.",
    level: "Intermediate to Advanced",
    outcome: "Use CDC and GBD datasets for population-level research.",
    deliverable: "One reproducible CDC- or GBD-based research proposal and analysis.",
    topics: [
      "Introduction to large public-health databases",
      "CDC data sources and identifying appropriate datasets",
      "Variable definitions, population and time-period awareness",
      "Downloading and preparing public-health data",
      "Descriptive epidemiology using surveillance data; trends over time and stratified analyses",
      "Global Burden of Disease (GBD) concepts",
      "Incidence, prevalence, mortality, YLDs, YLLs and DALYs",
      "Age-standardized rates and their interpretation",
      "Location, year, sex, age and cause dimensions",
      "Developing research questions from GBD data",
      "Visualizing and presenting population-level findings",
      "Limitations of secondary datasets and ecological analyses",
    ],
  },
  {
    code: "I",
    slug: "scientific-writing-and-publication",
    stage: "Throughout",
    title: "Scientific Writing and Publication",
    shortTitle: "Publication",
    oneLiner: "Write, submit and revise manuscripts.",
    level: "All levels",
    outcome: "Write, submit and revise manuscripts to publication standard.",
    deliverable: "A polished manuscript, a journal-selection rationale and a complete submission package.",
    topics: [
      "Writing a strong title and abstract",
      "Introduction: background → gap → objective",
      "Methods: enough detail for reproducibility",
      "Results: report without over-interpreting",
      "Discussion: principal findings → comparison → explanation → implications → limitations",
      "Tables and figures",
      "References and citation accuracy",
      "Reporting guidelines and checklists",
      "Journal selection, and recognizing predatory journals",
      "Cover letters",
      "Responding to reviewers, revision and resubmission",
    ],
  },
];

export const staged = modules.filter((m) => m.code !== "I");
export const writingModule = modules.find((m) => m.code === "I")!;

/** Handbook 9.1 — Research Tools and Standards taught in the Academy. */
export const toolkit = [
  { category: "Statistical analysis", items: ["R and RStudio", "Microsoft Excel"], use: "Data cleaning, analysis, visualization and reproducible workflows" },
  { category: "Reference management", items: ["Zotero", "Mendeley"], use: "Organizing literature and managing citations" },
  { category: "Literature databases", items: ["PubMed", "Google Scholar", "Scopus and Web of Science concepts"], use: "Literature and evidence searching" },
  { category: "Public-health data", items: ["CDC data sources", "Global Burden of Disease (GBD)"], use: "Population-level and secondary-data research" },
  { category: "Question frameworks", items: ["PICO", "PECO"], use: "Structuring research questions" },
  { category: "Reporting and appraisal", items: ["PRISMA", "GRADE", "Study-specific reporting guidelines", "Risk-of-bias tools"], use: "Transparent reporting and assessment of evidence quality" },
  { category: "Search vocabulary", items: ["MeSH and other controlled vocabularies", "Boolean operators"], use: "Systematic search-string construction" },
] as const;

/** Appendix A — glossary terms that appear in the curriculum. */
export const glossary = [
  { term: "CDC", meaning: "Centers for Disease Control and Prevention; a source of public-health surveillance data." },
  { term: "DALY", meaning: "Disability-adjusted life year: the sum of YLLs and YLDs." },
  { term: "DTA", meaning: "Diagnostic test accuracy." },
  { term: "GBD", meaning: "Global Burden of Disease; a framework and dataset for population health estimates." },
  { term: "GRADE", meaning: "A system for rating the certainty of evidence." },
  { term: "HR, OR, RR", meaning: "Hazard ratio, odds ratio and risk ratio." },
  { term: "I²", meaning: "A statistic describing the proportion of variation across studies due to heterogeneity." },
  { term: "MD, SMD", meaning: "Mean difference and standardized mean difference." },
  { term: "MeSH", meaning: "Medical Subject Headings; a controlled vocabulary used for indexing and searching literature." },
  { term: "PICO / PECO", meaning: "Population, Intervention (or Exposure), Comparison, Outcome: frameworks for structuring research questions." },
  { term: "PRISMA", meaning: "A reporting guideline and flow diagram for systematic reviews and meta-analyses." },
  { term: "TSA", meaning: "Trial Sequential Analysis." },
  { term: "YLD, YLL", meaning: "Years lived with disability; years of life lost." },
] as const;
